### ISSUE TITLE
Env properties are broken w/ deployer

### ISSUE THREAD

**Issue by gregturn** [spring-cloud/spring-cloud-spinnaker#36]
Patch to SC Deployer has moved all definition properties into Spring Application JSON, which breaks the deployer app.

**Comment by markpollack** [comment]
Can you be more specific in what is not working?  The spinnaker apps are boot apps so should pick up values in SAJ.  Btw, there were good reasons to do this on PCF.  Can't pass env-vars due to commonly encountered issues with relaxed binding and maps (not PCF specific) and command line args are also not a good option either (some interference with the build pack and escaping of some values - I forget the details) leaving only SAJ.  We will likely evolve the SPI to call out setting specifically env-var or command line args in the future, but not on a timescale that is relevant for us.

**Comment by gregturn** [comment]
Spinnaker modules are on Boot 1.2, so SAJ won't work right now. Creating a placeholder to track this currently open issue that would spring up if anyone rebuilt this app from scratch against latest deployer.

**Comment by gregturn** [comment]
Resolved by https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/62

**Comment by gregturn** [comment]
https://github.com/spring-cloud/spring-cloud-spinnaker/pull/40 fixes the immediate issue, but eventually migrating to https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/62 will be more efficient.

**Comment by gregturn** [comment]
I can't actually close this until I update Spring Cloud Spinnaker to use https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/3a8fd23a6a7186abf7e3a02455b4d3334a0ee757
