### ISSUE TITLE
getting bower task exception in mac os

### ISSUE THREAD

**Issue by ishwar1987** [spring-cloud/spring-cloud-spinnaker#71]
HI. 
I have downloaded the spring-cloud-spinnaker. After executing /mvnw clean package. I am getting the Failed to run task: 'bower install' failed. I have attached here trace log.
[bower.txt](https://github.com/spring-cloud/spring-cloud-spinnaker/files/456748/bower.txt)

**Comment by gregturn** [comment]
I grabbed a clean copy of spring-cloud-spinnaker, and see the same fault. Let me see what's happening with inuitcss.

**Comment by ishwar1987** [comment]
One more question. is there sequence for deploying app?. If it's not then can  i can push manually cloud-driver jar file in cloud foundry?

**Comment by gregturn** [comment]
There is no sequence, but the deployer app actually makes inline modifications to the JAR files before pushing them.

For example, the source code does NOT put clouddriver.yml inside the JAR. Netflix's deployment model wraps the JAR inside a debian package and brings along clouddriver.yml through a different mechanism than having it inside the JAR. spring-cloud-spinnaker actually opens up the JAR, while in flight, and inserts that file so that property settings will work properly.

We are working on a long term solution with Netflix to avoid this, but that hasn't taken root yet. Essentially, we are moving to create a clouddriver-app project that consumes clouddriver, and can have the clouddriver.yml file inside it.

**Comment by ishwar1987** [comment]
Thanks . Now its working. one question . after generating the spring-cloud-spinnaker-1.0.0.BUILD-SNAPSHOT.jar . Can i run this jar locally in apache tomcat?. I want to test this application locally before pushing to cloud foundry. is there any way?

**Comment by gregturn** [comment]
It's a good old Spring Boot uber jar. Just run it straight up. 

```
$ java -jar <spring cloud spinnaker>
```

**Comment by ishwar1987** [comment]
Hey,

What i meant is to deploy the jar file running into local system / my local tomcat to deep dive and capture more logs : error, debug, warn etc.. for troubleshooting

**Comment by ishwar1987** [comment]
Thanks a lot. i am able to run war file locally.  I need one more help. When clouddriver app or any other jar pushing to cloud foundry using api. How does i get logs when the jar file is uploaded to cloud foundry container. e.g. from locally i am deploying the cloud driver to cloud foundry. so  need to know each trace logs while uploading the jar file to cloud foundry.

**Comment by ishwar1987** [comment]
while deploying clouddriver from locally (running on local tomcat)to cloud foundry i got this exception . i have attached here
[clouddriver-error.txt](https://github.com/spring-cloud/spring-cloud-spinnaker/files/462377/clouddriver-error.txt)

**Comment by ishwar1987** [comment]
Is this is bug?

**Comment by gregturn** [comment]
It indicates the route it's trying to apply to clouddriver is somehow invalid. Can you manually apply the same route?

**Comment by gregturn** [comment]
The route should be clouddriver-<namespace>.<domain>.

**Comment by gregturn** [comment]
`clouddriver-{namespace}.{domain}`
